/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTeamsRouteImport } from './routes/_app.teams'
import { Route as AppTargetsRouteImport } from './routes/_app.targets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppRenewalsRouteImport } from './routes/_app.renewals'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppOperationsRouteImport } from './routes/_app.operations'
import { Route as AppMasterRouteImport } from './routes/_app.master'
import { Route as AppIncomeRouteImport } from './routes/_app.income'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppOperationsIndexRouteImport } from './routes/_app.operations.index'
import { Route as AppDealsIndexRouteImport } from './routes/_app.deals.index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app.accounts.index'
import { Route as AppOperationsReportsRouteImport } from './routes/_app.operations.reports'
import { Route as AppOperationsReimbursementsRouteImport } from './routes/_app.operations.reimbursements'
import { Route as AppOperationsPerformanceRouteImport } from './routes/_app.operations.performance'
import { Route as AppOperationsPayrollRouteImport } from './routes/_app.operations.payroll'
import { Route as AppOperationsExpensesRouteImport } from './routes/_app.operations.expenses'
import { Route as AppOperationsCommissionsRouteImport } from './routes/_app.operations.commissions'
import { Route as AppLeadsUnassignedRouteImport } from './routes/_app.leads.unassigned'
import { Route as AppDealsNewRouteImport } from './routes/_app.deals.new'
import { Route as AppDealsIdRouteImport } from './routes/_app.deals.$id'
import { Route as AppAccountsReportsRouteImport } from './routes/_app.accounts.reports'
import { Route as AppAccountsReceivablesRouteImport } from './routes/_app.accounts.receivables'
import { Route as AppAccountsPaymentsRouteImport } from './routes/_app.accounts.payments'
import { Route as AppAccountsPayablesRouteImport } from './routes/_app.accounts.payables'
import { Route as AppAccountsInvoicesRouteImport } from './routes/_app.accounts.invoices'
import { Route as AppAccountsInstallmentsRouteImport } from './routes/_app.accounts.installments'
import { Route as AppAccountsApprovalsRouteImport } from './routes/_app.accounts.approvals'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppTargetsRoute = AppTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppRenewalsRoute = AppRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsRoute = AppOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterRoute = AppMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsIndexRoute = AppOperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOperationsRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppOperationsReportsRoute = AppOperationsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppOperationsRoute,
} as any)
const AppOperationsReimbursementsRoute =
  AppOperationsReimbursementsRouteImport.update({
    id: '/reimbursements',
    path: '/reimbursements',
    getParentRoute: () => AppOperationsRoute,
  } as any)
const AppOperationsPerformanceRoute =
  AppOperationsPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AppOperationsRoute,
  } as any)
const AppOperationsPayrollRoute = AppOperationsPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppOperationsRoute,
} as any)
const AppOperationsExpensesRoute = AppOperationsExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppOperationsRoute,
} as any)
const AppOperationsCommissionsRoute =
  AppOperationsCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AppOperationsRoute,
  } as any)
const AppLeadsUnassignedRoute = AppLeadsUnassignedRouteImport.update({
  id: '/leads/unassigned',
  path: '/leads/unassigned',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsNewRoute = AppDealsNewRouteImport.update({
  id: '/deals/new',
  path: '/deals/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsIdRoute = AppDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsReportsRoute = AppAccountsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsReceivablesRoute = AppAccountsReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsPaymentsRoute = AppAccountsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsPayablesRoute = AppAccountsPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsInvoicesRoute = AppAccountsInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsInstallmentsRoute = AppAccountsInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsApprovalsRoute = AppAccountsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/income': typeof AppIncomeRoute
  '/master': typeof AppMasterRoute
  '/operations': typeof AppOperationsRouteWithChildren
  '/pipeline': typeof AppPipelineRoute
  '/renewals': typeof AppRenewalsRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/targets': typeof AppTargetsRoute
  '/teams': typeof AppTeamsRoute
  '/users': typeof AppUsersRoute
  '/accounts/approvals': typeof AppAccountsApprovalsRoute
  '/accounts/installments': typeof AppAccountsInstallmentsRoute
  '/accounts/invoices': typeof AppAccountsInvoicesRoute
  '/accounts/payables': typeof AppAccountsPayablesRoute
  '/accounts/payments': typeof AppAccountsPaymentsRoute
  '/accounts/receivables': typeof AppAccountsReceivablesRoute
  '/accounts/reports': typeof AppAccountsReportsRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/deals/new': typeof AppDealsNewRoute
  '/leads/unassigned': typeof AppLeadsUnassignedRoute
  '/operations/commissions': typeof AppOperationsCommissionsRoute
  '/operations/expenses': typeof AppOperationsExpensesRoute
  '/operations/payroll': typeof AppOperationsPayrollRoute
  '/operations/performance': typeof AppOperationsPerformanceRoute
  '/operations/reimbursements': typeof AppOperationsReimbursementsRoute
  '/operations/reports': typeof AppOperationsReportsRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/deals/': typeof AppDealsIndexRoute
  '/operations/': typeof AppOperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AppAnalyticsRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/income': typeof AppIncomeRoute
  '/master': typeof AppMasterRoute
  '/pipeline': typeof AppPipelineRoute
  '/renewals': typeof AppRenewalsRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/targets': typeof AppTargetsRoute
  '/teams': typeof AppTeamsRoute
  '/users': typeof AppUsersRoute
  '/accounts/approvals': typeof AppAccountsApprovalsRoute
  '/accounts/installments': typeof AppAccountsInstallmentsRoute
  '/accounts/invoices': typeof AppAccountsInvoicesRoute
  '/accounts/payables': typeof AppAccountsPayablesRoute
  '/accounts/payments': typeof AppAccountsPaymentsRoute
  '/accounts/receivables': typeof AppAccountsReceivablesRoute
  '/accounts/reports': typeof AppAccountsReportsRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/deals/new': typeof AppDealsNewRoute
  '/leads/unassigned': typeof AppLeadsUnassignedRoute
  '/operations/commissions': typeof AppOperationsCommissionsRoute
  '/operations/expenses': typeof AppOperationsExpensesRoute
  '/operations/payroll': typeof AppOperationsPayrollRoute
  '/operations/performance': typeof AppOperationsPerformanceRoute
  '/operations/reimbursements': typeof AppOperationsReimbursementsRoute
  '/operations/reports': typeof AppOperationsReportsRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/deals': typeof AppDealsIndexRoute
  '/operations': typeof AppOperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/master': typeof AppMasterRoute
  '/_app/operations': typeof AppOperationsRouteWithChildren
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/renewals': typeof AppRenewalsRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/targets': typeof AppTargetsRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/accounts/approvals': typeof AppAccountsApprovalsRoute
  '/_app/accounts/installments': typeof AppAccountsInstallmentsRoute
  '/_app/accounts/invoices': typeof AppAccountsInvoicesRoute
  '/_app/accounts/payables': typeof AppAccountsPayablesRoute
  '/_app/accounts/payments': typeof AppAccountsPaymentsRoute
  '/_app/accounts/receivables': typeof AppAccountsReceivablesRoute
  '/_app/accounts/reports': typeof AppAccountsReportsRoute
  '/_app/deals/$id': typeof AppDealsIdRoute
  '/_app/deals/new': typeof AppDealsNewRoute
  '/_app/leads/unassigned': typeof AppLeadsUnassignedRoute
  '/_app/operations/commissions': typeof AppOperationsCommissionsRoute
  '/_app/operations/expenses': typeof AppOperationsExpensesRoute
  '/_app/operations/payroll': typeof AppOperationsPayrollRoute
  '/_app/operations/performance': typeof AppOperationsPerformanceRoute
  '/_app/operations/reimbursements': typeof AppOperationsReimbursementsRoute
  '/_app/operations/reports': typeof AppOperationsReportsRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/deals/': typeof AppDealsIndexRoute
  '/_app/operations/': typeof AppOperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/accounts'
    | '/analytics'
    | '/clients'
    | '/dashboard'
    | '/income'
    | '/master'
    | '/operations'
    | '/pipeline'
    | '/renewals'
    | '/review'
    | '/settings'
    | '/targets'
    | '/teams'
    | '/users'
    | '/accounts/approvals'
    | '/accounts/installments'
    | '/accounts/invoices'
    | '/accounts/payables'
    | '/accounts/payments'
    | '/accounts/receivables'
    | '/accounts/reports'
    | '/deals/$id'
    | '/deals/new'
    | '/leads/unassigned'
    | '/operations/commissions'
    | '/operations/expenses'
    | '/operations/payroll'
    | '/operations/performance'
    | '/operations/reimbursements'
    | '/operations/reports'
    | '/accounts/'
    | '/deals/'
    | '/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/clients'
    | '/dashboard'
    | '/income'
    | '/master'
    | '/pipeline'
    | '/renewals'
    | '/review'
    | '/settings'
    | '/targets'
    | '/teams'
    | '/users'
    | '/accounts/approvals'
    | '/accounts/installments'
    | '/accounts/invoices'
    | '/accounts/payables'
    | '/accounts/payments'
    | '/accounts/receivables'
    | '/accounts/reports'
    | '/deals/$id'
    | '/deals/new'
    | '/leads/unassigned'
    | '/operations/commissions'
    | '/operations/expenses'
    | '/operations/payroll'
    | '/operations/performance'
    | '/operations/reimbursements'
    | '/operations/reports'
    | '/accounts'
    | '/deals'
    | '/operations'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/accounts'
    | '/_app/analytics'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/income'
    | '/_app/master'
    | '/_app/operations'
    | '/_app/pipeline'
    | '/_app/renewals'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/targets'
    | '/_app/teams'
    | '/_app/users'
    | '/_app/accounts/approvals'
    | '/_app/accounts/installments'
    | '/_app/accounts/invoices'
    | '/_app/accounts/payables'
    | '/_app/accounts/payments'
    | '/_app/accounts/receivables'
    | '/_app/accounts/reports'
    | '/_app/deals/$id'
    | '/_app/deals/new'
    | '/_app/leads/unassigned'
    | '/_app/operations/commissions'
    | '/_app/operations/expenses'
    | '/_app/operations/payroll'
    | '/_app/operations/performance'
    | '/_app/operations/reimbursements'
    | '/_app/operations/reports'
    | '/_app/accounts/'
    | '/_app/deals/'
    | '/_app/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/targets': {
      id: '/_app/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AppTargetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/renewals': {
      id: '/_app/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AppRenewalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations': {
      id: '/_app/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AppOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master': {
      id: '/_app/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AppMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/': {
      id: '/_app/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof AppOperationsIndexRouteImport
      parentRoute: typeof AppOperationsRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/operations/reports': {
      id: '/_app/operations/reports'
      path: '/reports'
      fullPath: '/operations/reports'
      preLoaderRoute: typeof AppOperationsReportsRouteImport
      parentRoute: typeof AppOperationsRoute
    }
    '/_app/operations/reimbursements': {
      id: '/_app/operations/reimbursements'
      path: '/reimbursements'
      fullPath: '/operations/reimbursements'
      preLoaderRoute: typeof AppOperationsReimbursementsRouteImport
      parentRoute: typeof AppOperationsRoute
    }
    '/_app/operations/performance': {
      id: '/_app/operations/performance'
      path: '/performance'
      fullPath: '/operations/performance'
      preLoaderRoute: typeof AppOperationsPerformanceRouteImport
      parentRoute: typeof AppOperationsRoute
    }
    '/_app/operations/payroll': {
      id: '/_app/operations/payroll'
      path: '/payroll'
      fullPath: '/operations/payroll'
      preLoaderRoute: typeof AppOperationsPayrollRouteImport
      parentRoute: typeof AppOperationsRoute
    }
    '/_app/operations/expenses': {
      id: '/_app/operations/expenses'
      path: '/expenses'
      fullPath: '/operations/expenses'
      preLoaderRoute: typeof AppOperationsExpensesRouteImport
      parentRoute: typeof AppOperationsRoute
    }
    '/_app/operations/commissions': {
      id: '/_app/operations/commissions'
      path: '/commissions'
      fullPath: '/operations/commissions'
      preLoaderRoute: typeof AppOperationsCommissionsRouteImport
      parentRoute: typeof AppOperationsRoute
    }
    '/_app/leads/unassigned': {
      id: '/_app/leads/unassigned'
      path: '/leads/unassigned'
      fullPath: '/leads/unassigned'
      preLoaderRoute: typeof AppLeadsUnassignedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals/new': {
      id: '/_app/deals/new'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof AppDealsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals/$id': {
      id: '/_app/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AppDealsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/reports': {
      id: '/_app/accounts/reports'
      path: '/reports'
      fullPath: '/accounts/reports'
      preLoaderRoute: typeof AppAccountsReportsRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/receivables': {
      id: '/_app/accounts/receivables'
      path: '/receivables'
      fullPath: '/accounts/receivables'
      preLoaderRoute: typeof AppAccountsReceivablesRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/payments': {
      id: '/_app/accounts/payments'
      path: '/payments'
      fullPath: '/accounts/payments'
      preLoaderRoute: typeof AppAccountsPaymentsRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/payables': {
      id: '/_app/accounts/payables'
      path: '/payables'
      fullPath: '/accounts/payables'
      preLoaderRoute: typeof AppAccountsPayablesRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/invoices': {
      id: '/_app/accounts/invoices'
      path: '/invoices'
      fullPath: '/accounts/invoices'
      preLoaderRoute: typeof AppAccountsInvoicesRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/installments': {
      id: '/_app/accounts/installments'
      path: '/installments'
      fullPath: '/accounts/installments'
      preLoaderRoute: typeof AppAccountsInstallmentsRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/approvals': {
      id: '/_app/accounts/approvals'
      path: '/approvals'
      fullPath: '/accounts/approvals'
      preLoaderRoute: typeof AppAccountsApprovalsRouteImport
      parentRoute: typeof AppAccountsRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsApprovalsRoute: typeof AppAccountsApprovalsRoute
  AppAccountsInstallmentsRoute: typeof AppAccountsInstallmentsRoute
  AppAccountsInvoicesRoute: typeof AppAccountsInvoicesRoute
  AppAccountsPayablesRoute: typeof AppAccountsPayablesRoute
  AppAccountsPaymentsRoute: typeof AppAccountsPaymentsRoute
  AppAccountsReceivablesRoute: typeof AppAccountsReceivablesRoute
  AppAccountsReportsRoute: typeof AppAccountsReportsRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsApprovalsRoute: AppAccountsApprovalsRoute,
  AppAccountsInstallmentsRoute: AppAccountsInstallmentsRoute,
  AppAccountsInvoicesRoute: AppAccountsInvoicesRoute,
  AppAccountsPayablesRoute: AppAccountsPayablesRoute,
  AppAccountsPaymentsRoute: AppAccountsPaymentsRoute,
  AppAccountsReceivablesRoute: AppAccountsReceivablesRoute,
  AppAccountsReportsRoute: AppAccountsReportsRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppOperationsRouteChildren {
  AppOperationsCommissionsRoute: typeof AppOperationsCommissionsRoute
  AppOperationsExpensesRoute: typeof AppOperationsExpensesRoute
  AppOperationsPayrollRoute: typeof AppOperationsPayrollRoute
  AppOperationsPerformanceRoute: typeof AppOperationsPerformanceRoute
  AppOperationsReimbursementsRoute: typeof AppOperationsReimbursementsRoute
  AppOperationsReportsRoute: typeof AppOperationsReportsRoute
  AppOperationsIndexRoute: typeof AppOperationsIndexRoute
}

const AppOperationsRouteChildren: AppOperationsRouteChildren = {
  AppOperationsCommissionsRoute: AppOperationsCommissionsRoute,
  AppOperationsExpensesRoute: AppOperationsExpensesRoute,
  AppOperationsPayrollRoute: AppOperationsPayrollRoute,
  AppOperationsPerformanceRoute: AppOperationsPerformanceRoute,
  AppOperationsReimbursementsRoute: AppOperationsReimbursementsRoute,
  AppOperationsReportsRoute: AppOperationsReportsRoute,
  AppOperationsIndexRoute: AppOperationsIndexRoute,
}

const AppOperationsRouteWithChildren = AppOperationsRoute._addFileChildren(
  AppOperationsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppMasterRoute: typeof AppMasterRoute
  AppOperationsRoute: typeof AppOperationsRouteWithChildren
  AppPipelineRoute: typeof AppPipelineRoute
  AppRenewalsRoute: typeof AppRenewalsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTargetsRoute: typeof AppTargetsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppDealsIdRoute: typeof AppDealsIdRoute
  AppDealsNewRoute: typeof AppDealsNewRoute
  AppLeadsUnassignedRoute: typeof AppLeadsUnassignedRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppMasterRoute: AppMasterRoute,
  AppOperationsRoute: AppOperationsRouteWithChildren,
  AppPipelineRoute: AppPipelineRoute,
  AppRenewalsRoute: AppRenewalsRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTargetsRoute: AppTargetsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppUsersRoute: AppUsersRoute,
  AppDealsIdRoute: AppDealsIdRoute,
  AppDealsNewRoute: AppDealsNewRoute,
  AppLeadsUnassignedRoute: AppLeadsUnassignedRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
