/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTeamsRouteImport } from './routes/_app.teams'
import { Route as AppTargetsRouteImport } from './routes/_app.targets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppRenewalsRouteImport } from './routes/_app.renewals'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppMasterRouteImport } from './routes/_app.master'
import { Route as AppIncomeRouteImport } from './routes/_app.income'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppDealsIndexRouteImport } from './routes/_app.deals.index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app.accounts.index'
import { Route as AppLeadsUnassignedRouteImport } from './routes/_app.leads.unassigned'
import { Route as AppDealsNewRouteImport } from './routes/_app.deals.new'
import { Route as AppDealsIdRouteImport } from './routes/_app.deals.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppTargetsRoute = AppTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppRenewalsRoute = AppRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterRoute = AppMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppLeadsUnassignedRoute = AppLeadsUnassignedRouteImport.update({
  id: '/leads/unassigned',
  path: '/leads/unassigned',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsNewRoute = AppDealsNewRouteImport.update({
  id: '/deals/new',
  path: '/deals/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsIdRoute = AppDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/income': typeof AppIncomeRoute
  '/master': typeof AppMasterRoute
  '/pipeline': typeof AppPipelineRoute
  '/renewals': typeof AppRenewalsRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/targets': typeof AppTargetsRoute
  '/teams': typeof AppTeamsRoute
  '/users': typeof AppUsersRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/deals/new': typeof AppDealsNewRoute
  '/leads/unassigned': typeof AppLeadsUnassignedRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/deals/': typeof AppDealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AppAnalyticsRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/income': typeof AppIncomeRoute
  '/master': typeof AppMasterRoute
  '/pipeline': typeof AppPipelineRoute
  '/renewals': typeof AppRenewalsRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/targets': typeof AppTargetsRoute
  '/teams': typeof AppTeamsRoute
  '/users': typeof AppUsersRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/deals/new': typeof AppDealsNewRoute
  '/leads/unassigned': typeof AppLeadsUnassignedRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/deals': typeof AppDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/master': typeof AppMasterRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/renewals': typeof AppRenewalsRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/targets': typeof AppTargetsRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/deals/$id': typeof AppDealsIdRoute
  '/_app/deals/new': typeof AppDealsNewRoute
  '/_app/leads/unassigned': typeof AppLeadsUnassignedRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/deals/': typeof AppDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/accounts'
    | '/analytics'
    | '/clients'
    | '/dashboard'
    | '/income'
    | '/master'
    | '/pipeline'
    | '/renewals'
    | '/review'
    | '/settings'
    | '/targets'
    | '/teams'
    | '/users'
    | '/deals/$id'
    | '/deals/new'
    | '/leads/unassigned'
    | '/accounts/'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/clients'
    | '/dashboard'
    | '/income'
    | '/master'
    | '/pipeline'
    | '/renewals'
    | '/review'
    | '/settings'
    | '/targets'
    | '/teams'
    | '/users'
    | '/deals/$id'
    | '/deals/new'
    | '/leads/unassigned'
    | '/accounts'
    | '/deals'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/accounts'
    | '/_app/analytics'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/income'
    | '/_app/master'
    | '/_app/pipeline'
    | '/_app/renewals'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/targets'
    | '/_app/teams'
    | '/_app/users'
    | '/_app/deals/$id'
    | '/_app/deals/new'
    | '/_app/leads/unassigned'
    | '/_app/accounts/'
    | '/_app/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/targets': {
      id: '/_app/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AppTargetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/renewals': {
      id: '/_app/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AppRenewalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master': {
      id: '/_app/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AppMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/leads/unassigned': {
      id: '/_app/leads/unassigned'
      path: '/leads/unassigned'
      fullPath: '/leads/unassigned'
      preLoaderRoute: typeof AppLeadsUnassignedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals/new': {
      id: '/_app/deals/new'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof AppDealsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals/$id': {
      id: '/_app/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AppDealsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppMasterRoute: typeof AppMasterRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppRenewalsRoute: typeof AppRenewalsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTargetsRoute: typeof AppTargetsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppDealsIdRoute: typeof AppDealsIdRoute
  AppDealsNewRoute: typeof AppDealsNewRoute
  AppLeadsUnassignedRoute: typeof AppLeadsUnassignedRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppMasterRoute: AppMasterRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppRenewalsRoute: AppRenewalsRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTargetsRoute: AppTargetsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppUsersRoute: AppUsersRoute,
  AppDealsIdRoute: AppDealsIdRoute,
  AppDealsNewRoute: AppDealsNewRoute,
  AppLeadsUnassignedRoute: AppLeadsUnassignedRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
